apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
  namespace: apps
  labels:
    app: pythonapp
spec:
  revisionHistoryLimit: 5
  replicas: 1
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: ghrc.io/daemondev/pythonapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 800Mi
            cpu: 0.5
      imagePullSecrets:
      - name: github
---
apiVersion: v1
kind: Service
metadata:
  name: pythonapp
  namespace: apps
  labels:
    app: pythonapp
spec:
  type: NodePort
  selector:
    app: pythonapp
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: pythonapp
  namespace: apps
  labels:
    app: pythonapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pythonapp
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
