apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
  namespace: apps
  labels:
    app: pythonapp
spec:
  revisionHistoryLimit: 5
  replicas: 1
  progressDeadlineSeconds: 240
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: ghrc.io/daemondev/pythonapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 300Mi
            cpu: 0.25
      imagePullSecrets:
      - name: github


